### ISSUE TITLE
Failed to run, status?

### ISSUE THREAD

**Issue by vmayoral** [axnedergaard/continuous-deep-q-learning#1]
Hey @axnedergaard, is great you started taking this request. What's the status? Is the code runnable at this point? I gave it a try and failed. I'm guessing your focus is on Python3.

Code fails because it can't find 

```
python3 experiment.py --environment MountainCarContinuous-v0 --learning_rate 0.01 --episodes 2000 --hidden_size 16 32 
200 --output results.txt
Traceback (most recent call last):
  File "experiment.py", line 10, in <module>
    import naf
  File "/Users/Victor/continuous-deep-q-learning/naf.py", line 16, in <module>
    from tensorflow.python.ops.distributions.util import fill_lower_triangular
ModuleNotFoundError: No module named 'tensorflow.python.ops.distributions'
```

I tried applying the following patch (couldn't find `tensorflow.python.ops.distributions.util` in any tf version):
```
@@ -13,7 +13,21 @@
 import tensorflow as tf
 import numpy as np
 import random
-from tensorflow.python.ops.distributions.util import fill_lower_triangular
+# from tensorflow.python.ops.distributions.util import fill_lower_triangular
+
+def fill_lower_triangular(x):
+    """
+    Numpy implementation of `fill_lower_triangular`.
+        Dumped from https://programtalk.com/vs2/python/13142/deep_recommend_system/java_predict_client/src/main/proto/tensorflow/contrib/distributions/python/kernel_tests/distribution_util_test.py/
+    """
+    x = np.asarray(x)
+    d = x.shape[-1]
+    # d = n(n+1)/2 implies n is:
+    n = int(0.5 * (math.sqrt(1. + 8. * d) - 1.))
+    ids = np.tril_indices(n)
+    y = np.zeros(list(x.shape[:-1]) + [n, n], dtype=x.dtype)
+    y[..., ids[0], ids[1]] = x
+    return y

```

but also failed miserably:

```
python3 experiment.py --environment MountainCarContinuous-v0 --learning_rate 0.01 --episodes 2000 --hidden_size 16 32 
200 --output results.txt
[2017-12-19 18:13:39,003] Making new env: MountainCarContinuous-v0
Traceback (most recent call last):
  File "experiment.py", line 149, in <module>
    rewards = recursive_experiment(keys, vals, [])
  File "experiment.py", line 64, in recursive_experiment
    rewards += recursive_experiment(keys, remaining_vals[1:], vals + [remaining_vals[0]])
  File "experiment.py", line 64, in recursive_experiment
    rewards += recursive_experiment(keys, remaining_vals[1:], vals + [remaining_vals[0]])
  File "experiment.py", line 64, in recursive_experiment
    rewards += recursive_experiment(keys, remaining_vals[1:], vals + [remaining_vals[0]])
  File "experiment.py", line 67, in recursive_experiment
    rewards += recursive_experiment(keys, remaining_vals[1:],  vals + [r])
  File "experiment.py", line 64, in recursive_experiment
    rewards += recursive_experiment(keys, remaining_vals[1:], vals + [remaining_vals[0]])
  File "experiment.py", line 64, in recursive_experiment
    rewards += recursive_experiment(keys, remaining_vals[1:], vals + [remaining_vals[0]])
  File "experiment.py", line 64, in recursive_experiment
    rewards += recursive_experiment(keys, remaining_vals[1:], vals + [remaining_vals[0]])
  [Previous line repeated 1 more times]
  File "experiment.py", line 67, in recursive_experiment
    rewards += recursive_experiment(keys, remaining_vals[1:],  vals + [r])
  File "experiment.py", line 64, in recursive_experiment
    rewards += recursive_experiment(keys, remaining_vals[1:], vals + [remaining_vals[0]])
  File "experiment.py", line 64, in recursive_experiment
    rewards += recursive_experiment(keys, remaining_vals[1:], vals + [remaining_vals[0]])
  File "experiment.py", line 64, in recursive_experiment
    rewards += recursive_experiment(keys, remaining_vals[1:], vals + [remaining_vals[0]])
  File "experiment.py", line 67, in recursive_experiment
    rewards += recursive_experiment(keys, remaining_vals[1:],  vals + [r])
  File "experiment.py", line 64, in recursive_experiment
    rewards += recursive_experiment(keys, remaining_vals[1:], vals + [remaining_vals[0]])
  File "experiment.py", line 64, in recursive_experiment
    rewards += recursive_experiment(keys, remaining_vals[1:], vals + [remaining_vals[0]])
  File "experiment.py", line 64, in recursive_experiment
    rewards += recursive_experiment(keys, remaining_vals[1:], vals + [remaining_vals[0]])
  [Previous line repeated 3 more times]
  File "experiment.py", line 60, in recursive_experiment
    return [experiment(dict(zip(keys,vals)))]
  File "experiment.py", line 78, in experiment
    agent = naf.Agent(args['v'], env.observation_space, env.action_space, args['learning_rate'], args['batch_normalize'], args['gamma'], args['tau'], args['epsilon'], args['hidden_size'], args['hidden_n'], args['hidden_activation'], args['batch_size'], args['memory_capacity'], args['load_path'], args['covariance'])
  File "/Users/Victor/continuous-deep-q-learning/naf.py", line 144, in __init__
    self.N = fill_lower_triangular(self.M.h)
  File "/Users/Victor/continuous-deep-q-learning/naf.py", line 24, in fill_lower_triangular
    d = x.shape[-1]
IndexError: tuple index out of range

```

Mind giving me a few pointers?

**Comment by axnedergaard** [comment]
Thank you for your interest!

The code runs properly on my machine and should replicate the results of the original paper. It is possible to compare the performance of various parameterisations across different OpenAI environments using command-line arguments (you can look at the 'run_experiments' script file for an example). Other argument options of particular interest are "-v", --render" and "--graph".

I am using Python 3.6.2 with TensorFlow 1.3.0. I received a similar error message when using an older TensorFlow version. Could you please confirm the version of TensorFlow used with Python3 on your machine:

`python3 -c "import tensorflow; print(tensorflow.__version__)"`

Alternatively, a quick hack would be to delete or comment out line 16 in 'naf.py' ('from tensorflow.python.ops.distributions.util import fill_lower_triangular') and use the command-line argument '--covariance identity' or '--covariance diagonal' when running the program. However, this would result in using a different covariance matrix from the original NAF paper:

The '--covariance' argument specifies the covariance matrix used in the advantage term of the NAF algorithm (current options are 'original', 'diagonal' and 'identity'). The covariance matrix used in the original NAF paper ('original') is obtained by populating the lower triangular of a matrix with terms from a neural network (this is where the 'fill_lower_triangular' function is used), exponentiating the diagonal terms and multiplying the resulting matrix by itself. The diagonal covariance matrix ('diagonal') is obtained by populating the diagonal of a matrix with terms from a neural network. The identity covariance matrix ('identity') simply uses an identity matrix.

Please let me know if anything is unclear or you have additional questions!

**Comment by axnedergaard** [comment]
As a side note, I am currently setting up an environment on a EC2 Amazon AWS server so I can run proper experiments and continue the project with some empirical guidance (my current computational resources are limited to a 2.3 GHz dual-core i3 processor). I am away travelling until mid-January, but I would be very excited to see more collaborators on the project!

**Comment by vmayoral** [comment]
> I am using Python 3.6.2 with TensorFlow 1.3.0. 

That did it. Thank you. I'll start analyzing code and implementation and contribute if possible.
Thanks.
